name: Deploy Log Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Security Check 1: tfsec
    - name: Run tfsec (Terraform Security Scanner)
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        working_directory: ./terraform
      continue-on-error: true

    # Security Check 2: Checkov
    - name: Run Checkov (Terraform & AWS Security Scanner)
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: ./terraform
        framework: terraform
      continue-on-error: true

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
